services:
  python:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - postgres-log:/var/log/postgresql:ro
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    volumes:
      - ./db/mysql/conf.d/:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  postgres:
    image: postgres:14
    command: -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./db/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/postgres/initdb.d:/docker-entrypoint-initdb.d
      - postgres-log:/var/log/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]

volumes:
  postgres-log:
